drop table IF EXISTS Employee;

create table Employee (
    ID INT NOT NULL,
    FIRST_NAME VARCHAR (50) NOT NULL,
    LAST_NAME VARCHAR (50) NOT NULL,
    DATE_OF_BIRTH DATE,
    WORKS_SINCE DATE,
    DEP_ID INT NOT NULL,
    SALARY DECIMAL(18,2),
    PRIMARY KEY (ID)
);
