;
CREATE USER IF NOT EXISTS "OUTLINE-DEV" SALT 'a247ab7be9bcdee0' HASH 'b522e3ac3aeb5f7769d026129a1518598441c9fa7e2aaf84dba2e404917dfb53' ADMIN;

CREATE CACHED TABLE PUBLIC.PARAGRAPH(
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  OWNER_ID VARCHAR(255),
  PARENTPARAGRAPH_ID VARCHAR(255),
  CHILDPARAGRAPHS_ORDER INTEGER
);
ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

INSERT INTO PUBLIC.PARAGRAPH(ID, NAME, OWNER_ID, PARENTPARAGRAPH_ID, CHILDPARAGRAPHS_ORDER) VALUES
  ('5b7f085c-33c1-4c07-b4db-78ef0a948233', 'root', 'a9b7c128-9d68-47dd-a7ab-53f07d741dab', NULL, NULL);

CREATE CACHED TABLE PUBLIC.PARAGRAPH_TAG(
  PARAGRAPH_ID VARCHAR(255) NOT NULL,
  TAGS_ID VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(PARAGRAPH_ID, TAGS_ID);

CREATE CACHED TABLE PUBLIC.ROLE(
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

INSERT INTO PUBLIC.ROLE(ID, NAME) VALUES
  ('444d3ffe-1ebe-4c07-a1a1-4abeb8e87774', 'ADMIN');

CREATE CACHED TABLE PUBLIC.TAG(
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.TOPIC(
  ID VARCHAR(255) NOT NULL,
  IMAGES VARCHAR(255),
  NAME VARCHAR(255) NOT NULL,
  OWNER_ID VARCHAR(255),
  PARAGRAPH_ID VARCHAR(255) NOT NULL,
  TOPICS_ORDER INTEGER
);
ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.TOPIC_TAG(
  TOPIC_ID VARCHAR(255) NOT NULL,
  TAGS_ID VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(TOPIC_ID, TAGS_ID);

CREATE CACHED TABLE PUBLIC.USER(
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);

INSERT INTO PUBLIC.USER(ID, NAME, PASSWORD) VALUES
  ('a9b7c128-9d68-47dd-a7ab-53f07d741dab', 'admin', '$2a$10$4NUDXX/5yFTsUGzUFG7EHOW374KS9OKduOlYmcMD8zOhEmu8v6Ud2');

CREATE CACHED TABLE PUBLIC.USER_ROLE(
  USER_ID VARCHAR(255) NOT NULL,
  ROLES_ID VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_BC PRIMARY KEY(USER_ID, ROLES_ID);


INSERT INTO PUBLIC.USER_ROLE(USER_ID, ROLES_ID) VALUES
  ('a9b7c128-9d68-47dd-a7ab-53f07d741dab', '444d3ffe-1ebe-4c07-a1a1-4abeb8e87774');

ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_SYFTR7GX86FWF7OX7BGVNNTA7 UNIQUE(NAME);

ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.FKQ0LSLEHWXA3NKKV3TJNOHIF8W FOREIGN KEY(PARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.FKNR1KQJM2HO0CNV344NAXCTH8V FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;

ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.FKAQ7NMC9MKS1WL3O6IO77V8THJ FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.FKTK57SNTG1BE4TXENN83LQ6231 FOREIGN KEY(PARENTPARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;

ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FK7QNWWE579G9FROLYPRAT52L4D FOREIGN KEY(ROLES_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FKC52D1RV3IJBPU6LO2V3REJ1TX FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;

ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.FK2U2FLCP4SNW5LLW8Y5VKDMCPW FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.FKDHMKOTMYYELUN0GHFN2JJMMJR FOREIGN KEY(PARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;

ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.FKETILC466TPWYNTUUXQBJ00M06 FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.FK688SUGEPY0EFQMQQQV9FNGA78 FOREIGN KEY(TOPIC_ID) REFERENCES PUBLIC.TOPIC(ID) NOCHECK;
