CREATE TABLE ICON (
    ID VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(255)
);
ALTER TABLE ICON ADD CONSTRAINT ICON_PK PRIMARY KEY(ID);


ALTER TABLE TOPIC ADD ICON_ID VARCHAR(255) NULL;
ALTER TABLE TOPIC ADD CONSTRAINT TOPIC_TO_ICON_FK FOREIGN KEY(ICON_ID) REFERENCES ICON(ID);

ALTER TABLE TOPIC ADD eol bit NULL default 0;

ALTER TABLE PARAGRAPH ADD ICON_ID VARCHAR(255) NULL;
ALTER TABLE PARAGRAPH ADD CONSTRAINT PARAGRAPH_TO_ICON_FK FOREIGN KEY(ICON_ID) REFERENCES ICON(ID);

ALTER TABLE PARAGRAPH ADD eol bit NULL default 0;
